"""users and all that

Revision ID: 0cfefa95d0ce
Revises: 
Create Date: 2024-10-02 17:51:58.776160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfefa95d0ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_slots_time_slot'), ['time_slot'], unique=True)

    op.create_table('seating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seating_capacity'), ['capacity'], unique=True)

    op.create_table('bookings',
    sa.Column('seating_id', sa.Integer(), nullable=False),
    sa.Column('booking_slots_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_slots_id'], ['booking_slots.id'], ),
    sa.ForeignKeyConstraint(['seating_id'], ['seating.id'], ),
    sa.PrimaryKeyConstraint('seating_id', 'booking_slots_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    with op.batch_alter_table('seating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seating_capacity'))

    op.drop_table('seating')
    with op.batch_alter_table('booking_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_slots_time_slot'))

    op.drop_table('booking_slots')
    # ### end Alembic commands ###
