"""empty message

Revision ID: 353279faf36e
Revises: 664b8f4d079a
Create Date: 2024-11-27 19:01:30.250618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353279faf36e'
down_revision = '664b8f4d079a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiting_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('added_on', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_waiting_list_requested_date'), ['requested_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiting_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiting_list_requested_date'))
        batch_op.drop_column('added_on')
        batch_op.drop_column('requested_date')

    # ### end Alembic commands ###
