"""initial commit

Revision ID: 46c2d1d74c25
Revises: 
Create Date: 2024-10-17 14:53:42.505432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c2d1d74c25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_slots_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_slots_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_slots_start_time'), ['start_time'], unique=False)

    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_name'), ['name'], unique=True)

    op.create_table('seating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seating_capacity'), ['capacity'], unique=False)
        batch_op.create_index(batch_op.f('ix_seating_table_number'), ['table_number'], unique=False)

    op.create_table('bookings',
    sa.Column('seating_id', sa.Integer(), nullable=False),
    sa.Column('booking_slots_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_slots_id'], ['booking_slots.id'], name='fk_booking_slots_id'),
    sa.ForeignKeyConstraint(['seating_id'], ['seating.id'], name='fk_seating_id'),
    sa.PrimaryKeyConstraint('seating_id', 'booking_slots_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    with op.batch_alter_table('seating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seating_table_number'))
        batch_op.drop_index(batch_op.f('ix_seating_capacity'))

    op.drop_table('seating')
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_name'))
        batch_op.drop_index(batch_op.f('ix_restaurant_address'))

    op.drop_table('restaurant')
    with op.batch_alter_table('booking_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_slots_start_time'))
        batch_op.drop_index(batch_op.f('ix_booking_slots_end_time'))
        batch_op.drop_index(batch_op.f('ix_booking_slots_date'))

    op.drop_table('booking_slots')
    # ### end Alembic commands ###
