"""empty message

Revision ID: 664b8f4d079a
Revises: 9d6a4e504a07
Create Date: 2024-11-04 10:56:37.571306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664b8f4d079a'
down_revision = '9d6a4e504a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiting_list', schema=None) as batch_op:
        batch_op.drop_index('ix_waiting_list_requested_date')
        batch_op.drop_column('requested_date')
        batch_op.drop_column('added_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiting_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('requested_date', sa.DATE(), nullable=True))
        batch_op.create_index('ix_waiting_list_requested_date', ['requested_date'], unique=False)

    # ### end Alembic commands ###
