"""empty message

Revision ID: 9d6a4e504a07
Revises: 46c2d1d74c25
Create Date: 2024-11-04 10:55:20.460713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6a4e504a07'
down_revision = '46c2d1d74c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_number', sa.String(length=20), nullable=False),
    sa.Column('seating_id', sa.Integer(), nullable=True),
    sa.Column('booking_slot_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_slot_id'], ['booking_slots.id'], name='fk_waitinglist_booking_slot_id'),
    sa.ForeignKeyConstraint(['seating_id'], ['seating.id'], name='fk_waitinglist_seating_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waiting_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiting_list_requested_date'), ['requested_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiting_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiting_list_requested_date'))

    op.drop_table('waiting_list')
    # ### end Alembic commands ###
