| Test Case ID | Test Description                                                                                                                                            | Tester         | Start Date  | End Date    | Status      |
|--------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------|-------------|-------------|-------------|
| TC_001       | Test login functionality for registered users: Ensure that only registered users can log in and access the system with valid credentials                    | Fernando Lopez | 2024-10-16  | 2024-10-17  | Not Started |
| TC_002       | Test account creation and registration process: Verify that new users can create an account and register successfully                                       | Reece Slade    | 2024-10-16  | 2024-10-17  | Not Started |
| TC_003       | Test security features (input validation and sanitization): Validate that the system prevents SQL injection and other malicious attacks through form inputs | Fernando Lopez | 2024-10-18  | 2024-10-19  | Not Started |
| TC_004       | Test database transaction handling: Ensure database transactions (for booking, modifying, or canceling) are completed successfully without data loss        | Reece Slade    | 2024-10-18  | 2024-10-19  | Not Started |
| TC_005       | Test system’s response to invalid inputs during booking: Ensure that invalid inputs (e.g., incorrect dates, missing fields) are handled gracefully          | Fernando Lopez | 2024-10-20  | 2024-10-21  | Not Started |
| TC_006       | Test reminder notifications for bookings: Ensure reminders are sent based on correct timings (e.g., 1 day before the booking)                               | Reece Slade    | 2024-10-20  | 2024-10-21  | Not Started |
| TC_007       | Test session timeout and user inactivity: Validate that the system logs out inactive users after a certain period                                           | Fernando Lopez | 2024-10-22  | 2024-10-23  | Not Started |
| TC_008       | Test multiple concurrent user logins: Ensure the system handles multiple users logging in simultaneously without issues                                     | Reece Slade    | 2024-10-22  | 2024-10-23  | Not Started |
| TC_009       | Test booking modification conflicts: Ensure proper error handling when multiple users attempt to modify the same booking simultaneously                     | Fernando Lopez | 2024-10-24  | 2024-10-25  | Not Started |
